### ISSUE TITLE
pls update to the latest react-native version 

### ISSUE THREAD

**Issue by jpca999** [Wolox/react-native-redux-toast#9]
![image](https://user-images.githubusercontent.com/1026325/32815083-2b968e22-c980-11e7-82b9-d686b9b2b043.png)

**Comment by ignaciosantise** [comment]
@jpca999 We will update this in a few days! Sorry for the inconvenience!

**Comment by ignaciosantise** [comment]
Solved in https://github.com/Wolox/react-native-redux-toast/pull/11
